server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api
    username: root
    password: gego
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
